description = "boingo"

[extensions]
"github.com/asg017/sqlite-http" = "v0.1.0-alpha.2"
"github.com/asg017/sqlite-vss" = "v0.0.2"
#"https://github.com/asg017/sqlite-path" = "v0.2.0-alpha.1"
#"github.com/asg017/sqlite-url" = "v0.1.0-alpha.3"
#"github.com/asg017/sqlite-html" = "v0.1.2-alpha.4"
#"github.com/asg017/sqlite-http" = "v0.1.0-alpha.2"
